[[headers]]
  for = "/Build/build.data.br"
  [headers.values]
    Content-Encoding = "br"
    Content-Type = "application/octet-stream"
	
[[headers]]
  for = "/Build/build.wasm.br"
  [headers.values]
    Content-Encoding = "br"
    Content-Type = "application/wasm"

[[headers]]                                                                      
  for = "/Build/build.loader.js"                                                             
  [headers.values]
    Content-Encoding = "js"
    Content-Type = "application/javascript"
	
[[headers]]                                                                      
  for = "/Build/build.framework.js.br"                                                             
  [headers.values]
    Content-Encoding = "br"
    Content-Type = "application/javascript"
